"""new fields in user model

Revision ID: 10ef539e7df2
Revises: b346e6eaa514
Create Date: 2020-06-12 16:39:51.603670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef539e7df2'
down_revision = 'b346e6eaa514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seem', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seem')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
